'\" t
.\"     Title: faillog
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/12/2012
.\"    Manual:  File Formats and Conversions
.\"    Source: shadow-utils 4.1.5
.\"  Language: English
.\"
.TH "FAILLOG" "5" "02/12/2012" "shadow\-utils 4\&.1\&.5" "File Formats and Conversions"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
faillog \- login failure logging file
.SH "DESCRIPTION"
.PP

/var/log/faillog
maintains a count of login failures and the limits for each account\&.
.PP
The file contains fixed length records, indexed by numerical UID\&. Each record contains the count of login failures since the last successful login; the maximum number of failures before the account is disabled; the line on which the last login failure occurred; the date of the last login failure; and the duration (in seconds) during which the account will be locked after a failure\&.
.PP
The structure of the file is:
.sp
.if n \{\
.RS 4
.\}
.nf
struct	faillog {
	short   fail_cnt;
	short   fail_max;
	char    fail_line[12];
	time_t  fail_time;
	long    fail_locktime;
};
.fi
.if n \{\
.RE
.\}
.SH "FILES"
.PP
/var/log/faillog
.RS 4
Failure logging file\&.
.RE
.SH "SEE ALSO"
.PP

\fBfaillog\fR(8)
